# Generated by Django 3.2.4 on 2023-10-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tono_bajo_alertas', models.CharField(max_length=3)),
                ('aplicacion', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('obtener_mas_informacion', models.CharField(max_length=3)),
                ('personal_interno_externo', models.CharField(max_length=100)),
                ('autenticacion_dos_factores', models.CharField(max_length=3)),
                ('encriptacion_datos', models.CharField(max_length=3)),
                ('monitoreo_seguridad_constante', models.CharField(max_length=3)),
            ],
        ),
    ]
